### test
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "{{$random.uuid}}@example.com"
}

### test rest
POST http://localhost:8080/admin/reset
Content-Type: application/json

{
  "email": "{{$random.uuid}}@example.com"
}

