### test reset
POST http://localhost:8080/admin/reset
Content-Type: application/json

{
  "email": "{{$random.uuid}}@example.com"
}

### test register new user
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "{{$random.uuid}}@example.com",
  "password": "password1"
}

### test user login
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email": "f36645e2-b89f-4f02-ae21-22c2e5844926@example.com",
  "password": "passwor2d1"
}

### test create chirp
POST http://localhost:8080/api/chirps
Content-Type: application/json

{
  "body": "Hello, world! 2",
  "user_id": "b4eacf70-5027-4276-9abc-389f34740922"
}

### test get chirps
GET http://localhost:8080/api/chirps
Accept: application/json

### test get chirps by id
GET http://localhost:8080/api/chirps/18a151d0-81cf-4d89-a823-ee1dddb2b8981
Accept: application/json


